### ISSUE TITLE
Members can manage their profile

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#10]
Every users should be able to set:
    - [x] Name
    - [x] Email
    - [x] Picture (gravatar)
    - [x] Link to twitter
    - [x] Link to github
    - [x] Description

**Comment by dechuck** [comment]
Question related to this issue. Right now, each `User` should have one `Member`. However, a member isn't created when a user is.

So, should we automatically create a member on the user `after_save`?

**Comment by sophiedeziel** [comment]
I started playing with it last week. The thing is that we also have members without users (because of the talks). We can collaborate on that one if you want!

**Comment by sophiedeziel** [comment]
oups, accidentally closed!

**Comment by dechuck** [comment]
@sophiedeziel I'd be happy to work with you on this one 😄 

Not all the members are linked to a user, but should all the users be linked to a member?
