### ISSUE TITLE
"Highlight" upcoming meetup and show summarized of previous events on homepage

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#103]

**Comment by benichu** [comment]
waiting for #42 to be merged before tackling this

**Comment by nicholasjhenry** [comment]
> "Highlight" upcoming meetup

Is this requirement not met with #59?

**Comment by kiramclean** [comment]
I can do this. What about news items.. sidebar?

**Comment by sophiedeziel** [comment]
We used to have them in the sidebar. You are free to experiment and try other solutions.

**Comment by kiramclean** [comment]
Just noticed we have an orphan `Meetup` model.. are all meetups now `Event`s?

**Comment by kiramclean** [comment]
Or maybe it's meant to be an option when creating an event..

**Comment by sophiedeziel** [comment]
Hmmmm Right now, the only events we got are meetups. That could be useful in the future when we'll have other kinds of events (workshops, railsbridge, hackathons, etc...)

Lets use the `Event` model for now because there is nothing in the admin to manage (and publish) meetups

**Comment by kiramclean** [comment]
Great!
