### ISSUE TITLE
Add Event#state

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#105]
This allows to propose events for the future without publishing them on the site.

- state values are: (proposed, scheduled)
- consider how this affects display events on the home page body, home page sidebar, and event index.

**Comment by itsWill** [comment]
I'll pick this one up as well since I touch it when I work on https://github.com/montrealrb/Montreal.rb/issues/48

**Comment by itsWill** [comment]
will wait till https://github.com/montrealrb/Montreal.rb/issues/128 is resolved to finish up this one
