### ISSUE TITLE
Simplify Event attributes

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#106]
Can `introduction` and `conclusion` be simplified to just `description`? Any need for these two attributes?

**Comment by benichu** [comment]
:+1:

**Comment by nicholasjhenry** [comment]
Great -- this is open for anyone to pick up.

**Comment by itsWill** [comment]
I can pick this one up as well as I work thorough https://github.com/montrealrb/Montreal.rb/issues/105
