### ISSUE TITLE
Creating an `Event` fails with no location

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#107]
<img width="1111" alt="screenshot 2015-12-04 11 20 58" src="https://cloud.githubusercontent.com/assets/40253/11594702/85494320-9a79-11e5-83e8-ec22d7b13d5a.png">

**Comment by cawel** [comment]
This is waiting on #116 to be resolved.

**Comment by sophiedeziel** [comment]
#116 is merged
