### ISSUE TITLE
Members submit to talk

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#11]
As a member, I want to be able to register my proposed talk with

- [x] title
- [x] Description
- [x] Level
- [x] Format (see #262 )
- [x] Link to my presentation slides

Non editable attributes for a non-admin user:

- [x] the talk should have the `proposed` state
- [x] the talk should be linked to my member

UI :

- [x] I should see a confirmation page with my talk's details and that it is in proposed state
- [x] I should see the link to submit a talk in the dropdown menu of my user on the navbar

**Comment by sophiedeziel** [comment]
done!
