### ISSUE TITLE
Setup newrelic

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#111]

**Comment by mathieugagne** [comment]
I stopped doing it because I never look at it. But since it's as simple as installing a Heroku plugin.. :+1:

**Comment by benichu** [comment]
@mathieugagne please assign an issue to yourself before working on it. especially since someone else was already assigned to it :smile:

**Comment by mathieugagne** [comment]
Hahaha I thought I was already assigned to this one. Clearly this assignment thing is a problem for me.
