### ISSUE TITLE
Add `published_by` to events, jobs, news

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#115]
This would assign the current user to these models

**Comment by cawel** [comment]
So we add `user_id` or `member_id` to all those 3 models?
All those new fields as required (both in db and model)?

**Comment by nicholasjhenry** [comment]
> So we add user_id or member_id to all those 3 models?

`user_id`

> All those new fields as required (both in db and model)?

Yes, please.
