### ISSUE TITLE
Top left montreal.rb "logo" should be clickable and include official logo

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#118]
- [x] clickable
- [ ] logo 

![](http://storage.thouret.com.s3.amazonaws.com/monosnap/Montreal.rb_2015-12-04_14-26-11.png)

**Comment by benichu** [comment]
https://files.slack.com/files-pri/T04ND4FMG-F04ND7X9C/mtlrb-logo.png

**Comment by mathieugagne** [comment]
- This logo is in English only.
- It has a solid white background.
- The red of the logo doesn't play well with the pinkish-red header background. We would need to change one of the 2 (logo or background-color)

**Comment by benichu** [comment]
@mathieugagne where can we go to the source?
Found that in slack :(

**Comment by mathieugagne** [comment]
@vivrass Do you have the source file? Do we know who designed this logo?

**Comment by mathieugagne** [comment]
Oh crap! I'm so sorry @mdeloupy I just saw this was assigned to you. My bad. I'll leave all the logo stuff up to you

**Comment by vivrass** [comment]
@mathieugagne   I put them on Slack

**Comment by benichu** [comment]
[2015_12_05_montreal.rb logos.zip](https://github.com/montrealrb/Montreal.rb/files/52882/2015_12_05_montreal.rb.logos.zip)

**Comment by benichu** [comment]
@mdeloupy can you attach the screenshot with the logo that you showed me?
Just to document that it does not look good.

**Comment by kloklo90** [comment]
Was this already taken care of because it already links to root path? The logo is not there but my understanding is that we do not want the new logo to be placed on the current red banner. I can change the header banner color if everyone wants the new logo to be put on the website.

**Comment by kloklo90** [comment]
![image](https://cloud.githubusercontent.com/assets/6946085/22048064/b3a4d7f8-dcf8-11e6-9947-817e3188d8c9.png)
Would something like this suit the newer logo. I just put these together in 5 minutes on visio to be able to visualize wat it could look like.

**Comment by steakunderscore** [comment]
This should be closed, current design is better than anything mentioned in this ticket.

**Comment by sophiedeziel** [comment]
Thanks @steakunderscore :)
