### ISSUE TITLE
Add "Demo" seeds

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#123]
Similar to how the Spree project provide Demo data. This would be helpful to contributors to see their local version working with data.

**Comment by cawel** [comment]
No objection to leverage the `Faker` gem for the seeding?

Also, could you be a bit more specific about what you like about Spree's seeding? Do you mean:

* the [encapsulation into a gem](https://github.com/spree/spree/tree/3-0-stable/sample)?
* the loading of [separate model-specific files](https://github.com/spree/spree/blob/3-0-stable/sample/lib/spree_sample.rb)?

Something else?

**Comment by nicholasjhenry** [comment]
> No objection to leverage the Faker gem for the seeding?

No at all.

> the encapsulation into a gem?

might be overkill for our project

> the loading of separate model-specific files

yes. Demo seeds would be loaded when the `DEMO=1` is set. It could be as simple as this:

```ruby
# seeds.rb

require_relative './seeds/demo/seeds.rb' if ENV['DEMO'] 

# db/seeds/demo.rb

demo_path = Rails.root.join('db','seeds','demo')

Dir.glob(File.join(demo_path, '**/*.{rb}')).each { |file| require file }
```

**Comment by steakunderscore** [comment]
I'm not completely clear as to what the `demo` seeds would be used for. I have added a bunch of seeds to get me started with development on the project. See my PR #175.

If you are able to give me some guidance I would be happy to change/fix anything.

**Comment by steakunderscore** [comment]
Can this be closed now?
