### ISSUE TITLE
Automatically display gravatar of talk#presenter when displaying on website

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#127]

**Comment by benichu** [comment]
related to #126

**Comment by mathieugagne** [comment]
Would a simple helper method that takes the email as an input work? I don't see the need for yet another gem.

**Comment by mathieugagne** [comment]
What do you refer to when you say "Automatically"?

**Comment by benichu** [comment]
Meaning that when we define the "member" assigned to a "talk" as a "presenter", the system should use that "member's email" to automatically display the avatar next to the talk on the website

**Comment by benichu** [comment]
@mathieugagne I was not mentioning any gems ;)

**Comment by benichu** [comment]
and we should not have to add an email field if we apply this: https://github.com/montrealrb/Montreal.rb/wiki/Domain-Model

**Comment by mathieugagne** [comment]
related to #60

**Comment by kiramclean** [comment]
I can do this one.. I know it's not priority, but images are not being displayed properly for talk presenters right now and this will it pretty easily.
