### ISSUE TITLE
Manage and display locations assigned to events

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#13]
As an organizer, I want to have a list of available meet-up places

    Name
    Address
    Directions
    Google Map

- [x] manage locations
- [x] assign locations to an event
- [x] display location on event page

**Comment by GalkaS** [comment]
Hey, I'll try this one :)

**Comment by nicholasjhenry** [comment]
Just a heads up, there are still open tasks on this if anyone is interested.

https://github.com/montrealrb/Montreal.rb/issues/13#issue-44318215
