### ISSUE TITLE
Discuss what code styling rule should be enforced to limit houndci warnings to important things

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#131]

**Comment by benichu** [comment]
cc @montrealrb/organizers

**Comment by mathieugagne** [comment]
Damn quotes.. I like having the same quotes all around but it _is_ somehow a little bit painful.

**Comment by benichu** [comment]
should we activate this: https://github.com/montrealrb/Montreal.rb/blob/master/.ruby-style.yml#L39-L41

**Comment by benichu** [comment]
remove this warning: ![](http://storage.thouret.com.s3.amazonaws.com/monosnap/chore_Fixes_42_-_Import_old_wordpress_data_and_convert_to_markdown_by_benichu__Pull_Request_98__montrealrbMontreal.rb_2015-12-06_06-22-06.png)

I am all for limiting line length, but can we have a bit of slack.

**Comment by benichu** [comment]
Added rubocop to run checks locally and experimenting with removing double-quotes enforcing :disappointed: and longer line length :smile: 

https://github.com/montrealrb/Montreal.rb/blob/master/.rubocop.yml

**Comment by nicholasjhenry** [comment]
Here's the current config I'm using on my current project. Basically we disabled everything and enabled things when we saw a style violation that we thought was important. This seemed like a better way to go than just enabling everything by default. Some preferences that get my vote:

1. Double Quotes
2. Longer line length ~100

https://gist.github.com/nicholasjhenry/5415cee34c9005a2a63d
