### ISSUE TITLE
Manage and display events

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#14]
As an organizer, I want to be able to be able to create a monthly event

    Choose a meet-up place
    Choose 2 talks
    Add an introduction + conclusion (french + english)

- [x] manage events in the admin
- [x] display events
- [x] render the show view
- [x] add missing attributes to the index view
- [x] link title on the index view

**Comment by nmoller** [comment]
I'm on it.

**Comment by nicholasjhenry** [comment]
Admin completed for this, thanks! We just need to display events on the site.

**Comment by nicholasjhenry** [comment]
Some outstanding tasks on this:

- [ ] render the show view
- [ ] add missing attributes to the index view
- [ ] link title on the index view

**Comment by benichu** [comment]
I'll take care of those tasks (on the NewsItem model) in my migration branch #42 as this is helpful for data cleanup
