### ISSUE TITLE
Implement level when displaying talks

### ISSUE THREAD

**Issue by itsWill** [montrealrb/Montreal.rb#142]
It would be useful if talks could have a level associated with them a la [seattle.rb](http://www.seattlerb.org/talks) like beginner, intermediate, and advanced. We could easily implement this using an enum.

**Comment by cawel** [comment]
Good idea! And it's been planned already, as you can see with the `level` field in the `Talk` model in the [object model diagram](https://github.com/montrealrb/Montreal.rb/issues/47#issuecomment-158508238) :)

We could consider that issue as the actual task to implement it though.

**Comment by itsWill** [comment]
whoops totally missed that edited to reflect that

**Comment by karimmtarek** [comment]
Related to #60 and I'm already on it.
