### ISSUE TITLE
Keep track of runtime errors on production (and get notified)

### ISSUE THREAD

**Issue by karimmtarek** [montrealrb/Montreal.rb#143]
There are lots of services doing this, and I'm not sure if we are using any service for that. 
So in case we are not using any service, I wanted to suggest [Bugsnag](https://bugsnag.com/features) I'm using it for one of my personal projects, it dose the job and it's [free for open source projects](https://bugsnag.com/blog/bugsnag-loves-open-source) :)

**Comment by benichu** [comment]
you read my mind :)
let's try bugsnag, I'll set it up soon.
