### ISSUE TITLE
ActionView::Template::Error in admin/events#index

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#146]
## Exception in Montreal.rb

**ActionView::Template::Error** in **admin/events#index**
undefined method &#x60;to_model&#x27; for #&lt;TBALocation:0x007f23890dfe90&gt;

[View on Bugsnag](https://bugsnag.com/montreal-dot-rb/montreal-dot-rb/errors/5666d7a38f2356495b6f5c68?event_id=5666d7a3adfc32c514eea19e)

## Stacktrace

    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/polymorphic_routes.rb:297 - handle_list
    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/polymorphic_routes.rb:206 - polymorphic_method
    vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/polymorphic_routes.rb:134 - polymorphic_path

[View full stacktrace](https://bugsnag.com/montreal-dot-rb/montreal-dot-rb/errors/5666d7a38f2356495b6f5c68?event_id=5666d7a3adfc32c514eea19e)

**Comment by itsWill** [comment]
I think we should remove the `TBALocation` class an just have a nil value represent a TBA location.  This not only fixes the above issue, but I also don't think modeling a TBA location as class is the best way to do this, it would be better modeled as a entry in our database, that could be selected in the admin as in the picture: ![screen shot 2015-12-08 at 12 12 01 pm](https://cloud.githubusercontent.com/assets/6386302/11662524/13707aaa-9da5-11e5-9355-21f90f532c02.png)

**Comment by itsWill** [comment]
previous discussion [here](https://github.com/montrealrb/Montreal.rb/pull/116#discussion_r46749166)

**Comment by sophiedeziel** [comment]
The TBALocation has been removed with https://github.com/montrealrb/Montreal.rb/pull/116
