### ISSUE TITLE
NoMethodError in Admin::Events#index

### ISSUE THREAD

**Issue by karimmtarek** [montrealrb/Montreal.rb#147]
I got that error while creating an event, without having a location in the db, so I went back and created a location, and tried to create an events but as you can see...

![screen shot 2015-12-08 at 9 56 45 am](https://cloud.githubusercontent.com/assets/5586031/11658726/15ff0650-9d92-11e5-9283-8f9ff6bd396f.png)

**Comment by itsWill** [comment]
related to: https://github.com/montrealrb/Montreal.rb/issues/146

**Comment by benichu** [comment]
duplicate to #146
