### ISSUE TITLE
Signing in with github does not seem to be working, any missing configurations?

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#154]

**Comment by nicholasjhenry** [comment]
GITHUB_KEY
GITHUB_SECRET

It's been a while since I've done this. Probably need to register an OAuth app:

https://github.com/organizations/montrealrb/settings/applications/new

**Comment by benichu** [comment]
`GITHUB_KEY` and `GITHUB_SECRET` are set as Heroku ENV variables, I don't who did it and if they are valid...

**Comment by nicholasjhenry** [comment]
@sophiedeziel did yesterday.

**Comment by sophiedeziel** [comment]
Yes I did :)

For your own development machine, you should create your own github app to have the callback url set to `localhost:your_port` and set the env vars. I created an app specially for our heroku instance and I have to remember changing the callback url when we point montrealrb.com to it.

**Comment by em77** [comment]
@benichu, were you able to get it working?

**Comment by benichu** [comment]
@em77 Will try again after the site "launch", until then we have desactivated the signup (just removed the link actually)

**Comment by sophiedeziel** [comment]
It is working in prod, is it still an issue, @benichu?

**Comment by benichu** [comment]
Maybe it's because I already have an account with my github email.
When I try to "Sign in with github", I am redirected to github, I can login to github, then I am redirected back to the montreal.rb signup page, and it asks me for an email and password/password_confirmation after submitting it proceeds to tell me that my "email has already been taken"...

Are my expectations wrong? Should it be normal behaviour? If it works for everyone but me, and I am a edge-case (even a valid one), please close that issue...

**Comment by sophiedeziel** [comment]
Oh, your expectations are not wrong. I would also want my existing account to be linked to the github oauth mechanism. I'll investigate a little to see if it's a config thing...

**Comment by benichu** [comment]
Thanks @sophiedeziel !

**Comment by sophiedeziel** [comment]
https://github.com/intridea/omniauth/wiki/Managing-Multiple-Providers

That would be part of the solution because it links the identity to the user instead of both being the same object. What we would do is to "find_or_create" the user wit the email when the identity is not found. 

<img width="495" alt="screen shot 2016-03-07 at 5 53 26 pm" src="https://cloud.githubusercontent.com/assets/1037105/13586203/9357de50-e48d-11e5-89bb-2fde97e2488c.png">
