### ISSUE TITLE
Manage and display organizations

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#18]
As a company, I'd like to have a page on the website
    Name
    Address
    Logo
    Description
    List of members working there
    List of members who can manage the company

**Comment by nicholasjhenry** [comment]
While I think it's a great idea to have a directory of companies/organizations I'm concerned with the feature: `List of members working there`.

**Comment by syed** [comment]
Working on this ....

**Comment by nicholasjhenry** [comment]
Some outstanding tasks on this:

- [ ] link to organizations from the navigation
- [ ] link organization index view to show view
- [ ] implement image uploader for logo
