### ISSUE TITLE
HTTPS all the things!!

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#228]
Heroku announced something really exciting : free SSL encryption support!
https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

With Let's Encrypt initiatives, we can get a free certificate: 
https://letsencrypt.org/

Let's force HTTPS!

(note: I'm assigning to me because I have admin access to the heroku account)

**Comment by KentCrutchfield** [comment]
If you want to do this for free in less than 30 seconds, the URL could be https://montrealrb.herokuapp.com

(No shame in letting everyone know it is on Heroku!)

**Comment by fbernier** [comment]
There is https://github.com/dmathieu/sabayon which could be a good solution to start with.

**Comment by em77** [comment]
I just used [sabayon](https://github.com/dmathieu/sabayon) to implement Lets Encrypt certificates on two Rails apps I'm maintaining on Heroku and it worked pretty smoothly. Note that after you run it, you need to change the DNS settings to point to a different CNAME which you can see afterward when running `heroku domains`. That's a point I missed at first that made it take longer than necessary.

**Comment by sophiedeziel** [comment]
https://blog.heroku.com/announcing-automated-certificate-management

**Comment by sophiedeziel** [comment]
Status update on this issue: 

🎉  we changed hosting provider 🎉 
Speedy rails is providing us with an awesome server and Cloudflare. so I was able to use letsencrypt. Certificates were created successfully. Now, all that we have to do is enforce it (rails config to redirect all http to https).
