### ISSUE TITLE
Feature: Embed youtube videos in talks

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#277]
The description is self-explanatory!
On the event view, when the talk is in the past, display the youtube video embeded. 

Maybe the description should be shortened with a "Read more" (all front-end, with a slide down animation)

**Comment by opiation** [comment]
This seems like potentially two different features that may be independent of each other.  Perhaps the truncated _preview_ description could be tracked in a separate issue.

Regarding the YouTube vids, where are the videos currently stored/displayed?  In looking at the past year or so of events, on the **events** page, I did not find any YouTube links.  Have I missed something obvious or are they not displayed anywhere and simply stored in a DB or something?

**Comment by sophiedeziel** [comment]
Haha not so self-explanatory after all.

Videos are on youtube and the links are not stored in the database yet. We only started recording them in September and shared the links through slack, facebook and twitter.

It should (obviously) only be visible on past events. 

The "Read More" could be a separate issue, let's display the thing first.

**Comment by opiation** [comment]
As far as I can tell, there are 2 videos available (at least on the [**Montreal.rb** channel][0]):

- [Roberta Voulon](https://www.youtube.com/watch?v=GSmwG2aZwEI)
- [Anna Filina](https://www.youtube.com/watch?v=s0gKePTF31U)

Is this correct?

[0]: https://www.youtube.com/channel/UCmq5nOaMp18rcljeFocUUqw/videos

**Comment by sophiedeziel** [comment]
Yes, and three others are coming.

**Comment by opiation** [comment]
Thanks for your feedback.  I propose the following:

- Add a new `youtube_id` field to the `Talk` model to hold YouTube video ID hash (e.g: **GSmwG2aZwEI**)
- Add `youtube_id` input in related admin form
- When listing past events/talks, YouTube players are embedded between the talk title and the talk level (effectively placing the level below the video)
- The video pane should be approximately the width of the column containing the talk description

Does this sound about right?

**Comment by sophiedeziel** [comment]
Yes! I'll review when I find a few minutes. Thank you for your pull-request!
