### ISSUE TITLE
Implement pages in admin and use them

### ISSUE THREAD

**Issue by steakunderscore** [montrealrb/Montreal.rb#280]
Currently the pages is static HTML in the views. It would be nice if we could instead add, update and remove pages with ease from the admin panel. This involves fixing the code and pre-populating the pages table with data from the html currently in the views.

- [x] Add page content to existing pages table in database
  - [x] Add existing data from views as markdown in migration
- [x] Add admin section for editing pages in markdown
- [x] Fix view to display content
- [x] Fix routes and links
- [x] Remove old routes, controller actions  and views ( `PagesController#about`, `PagesController#code_of_conduct` ).

**Comment by sophiedeziel** [comment]
Done.
