### ISSUE TITLE
Add mentions of our social media platforms

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#284]
Right now, there is no mention of how to be informed of our events on other platforms. We need to 

- [x] Remove the mention of the Google Group in the footer (I got only spam in the past year)
- [x] Add a link to the facebook group in the footer
- [x] Add a link to twitter in the footer
- [x] Add a link to our meetup page in the footer
- [x] Add a link to our youtube channel in the footer
- [x] Add a link to our website subscribe page in the footer

In the about section, we should add all those links but also explain that by signing up to the website, they'll get access to our Slack Team.

Here are the links:
https://www.meetup.com/mtl-rb/
https://www.facebook.com/montrealrb
https://twitter.com/montrealrb
https://www.youtube.com/channel/UCmq5nOaMp18rcljeFocUUqw

**Comment by bellef** [comment]
- [x] Remove the mention of the Google Group in the footer (I got only spam in the past year)
- [x] Add a link to the facebook group in the footer
- [x] Add a link to twitter in the footer #=> Already there
- [x] Add a link to our meetup page in the footer
- [x] Add a link to our youtube channel in the footer
- [x] Add a link to our website subscribe page in the footer
- [x] Add all those links in the about section
- [ ] Validate wording

[Here's the PR](https://github.com/montrealrb/Montreal.rb/pull/297)

Can we validate the wording together @sophiedeziel ? :)

**Comment by bellef** [comment]
@sophiedeziel I was not up to date with the master branch and I did not see that the work was already done. Can we close the issue if there's nothing more to do?

**Comment by sophiedeziel** [comment]
Thank you @bellef for your contributions! It will be deployed soon.
