### ISSUE TITLE
Events categorised as "past" too soon

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#286]
Events are defined as "past" when the start time is in the past. So, when a Meetup is scheduled at 18:30 PM and it's 18:31, it is already marked as past.

This is not very convenient on the home page, because the next event will show up first and people just a little bit late might be confused. Like thinking they are heading to the wrong venue.

With that in mind, I think there should be another special category: Today's event. I should be right on top, followed by next events (if any) and past events.

**Comment by opiation** [comment]
If it helps any, I think there could be an easy win here to remain almost as elegant as [`partition`][0] from the home controller...

```ruby
grouped_events = Event.published.includes(
  :translations,
  :location,
  :sponsors,
  talks: %i(member translations)
).order(:starts_at).limit(5).group_by do |event|
  if event.to_date < Date.today
    :past
  elsif event.to_date == Date.today
    :today
  else
    :future
  end
end
@todays_events, @past_events, @future_events = grouped_events.values_at(
  :today, :past, :future
)
```

...and then updating the view accordingly.

[0]: https://github.com/montrealrb/Montreal.rb/blob/master/app/controllers/home_controller.rb#L5
