### ISSUE TITLE
Add a `bin/setup` script to automate setting up a new development environment

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#29]
Answering the question:

> How do I get this running on my machine?

**Comment by benichu** [comment]
Also update the README accordingly.

**Comment by sophiedeziel** [comment]
Thanks Ben! :+1: 
It was my plan for tonight to prepare the repository, so everything you pointed out today id very helpful :smile:

**Comment by sophiedeziel** [comment]
We only need to `bundle install` and `rake db:setup`. Is it really needed at this point?

**Comment by benichu** [comment]
IMHO, it's always good to automate/formalize recurrent tasks into well defined, easy to run (by humans or machines) scripts.
Starting that process at the beginning of a project offer future users and system evolutions a good foundation.
I'll start something up, we'll take it from here...

**Comment by benichu** [comment]
it will be a small script, but with more than just `bundle install` and `rake db:setup` :wink:
