### ISSUE TITLE
Remove `titlelize` from views

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#291]
It breaks CamelCase words (and company names) and acronyms. Let the author of the post titlelize properly. 

API and GitHub are butchered here:
<img width="798" alt="screen shot 2018-04-18 at 2 03 01 pm" src="https://user-images.githubusercontent.com/1037105/38950382-542fb798-4313-11e8-8baa-9ca958d09028.png">

**Comment by bellef** [comment]
https://github.com/montrealrb/Montreal.rb/pull/292
Let me know if anything's missing :)
