### ISSUE TITLE
Make README more informational and helpful

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#30]
# Project Name

## Description

> Include the answer to the age-old question "What problem is this project solving?"
> Add a  wireframe, logo or screenshot

## Requirements

> Outline of the technologies in the project (framework, database, ruby version...)
>
> Links to any related projects
>
> Links to online tools related to the application (e.g.: Links to the Basecamp project, a link to the dropbox where all the wireframes are stored...)
>
> External services or processes (sidekiq, amazon S3, postmark...)

## Development Setup

> How to install the project ? Git clone, install dependencies/libraries, how to launch the server...

## Testing

> How to run the tests ?

## Deploy

> Staging and Production environment sections (one section per environment) should provide any information a developer might need to know about these environments.

## Bug Tracker

> Where to post issues/task for the project ?

## License

> probably MIT

**Comment by benichu** [comment]
Also, extract requirements in separate file in `./doc`

**Comment by sophiedeziel** [comment]
It's still can be improved, but I filled out all the sections!
