### ISSUE TITLE
Update to rails 4.2+

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#31]

**Comment by benichu** [comment]
or rails 5?

**Comment by sophiedeziel** [comment]
Rails 5 is very tempting :smile: But it's not even in beta! Let's update to 4.2 first, and we'll see then for 5. Is that good for you?

**Comment by benichu** [comment]
Fine by me.

As a side note, I just started our first rails5 api at work... I am a cowboy :D
But I wouldn't do that for Montreal.rb's website.

**Comment by sophiedeziel** [comment]
That's soooo cool!
