### ISSUE TITLE
Ready to be deployed to heroku

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#43]
- [x] Deploy procedure/scripts
- [x] Continuous deployment :question: 
- [x] montrealrb.com DNS switch ready (who has credentials for domain management and where...)

**Comment by sophiedeziel** [comment]
We already have Travis working, we can use it in our advantage :smile:

**Comment by vivrass** [comment]
I am the one who is controlling the DNSes. I can transfer the ownership to someone else ( @sophiedeziel or a generic Montreal.rb user)

**Comment by sophiedeziel** [comment]
Transfer it to me first and I'll set up proper "accounts and credential" sharing when it will be needed

**Comment by sophiedeziel** [comment]
What I did:
-[x] Heroku app setup
-[x] Travis-CI config
-[x] Travis-CI deploying master to heroku on each successful build
-[ ] Pointing DNS to heroku when the app is ready to use

https://montreal-rb.herokuapp.com/
