### ISSUE TITLE
Create a mockup to drive features

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#46]

**Comment by nicholasjhenry** [comment]
Below is a wire-frame and site map  of the home page. I won't provide much explanation here as I think it is pretty straight forward. The main body of the home page will be an aggregator for recent events, news and job postings. The side bar will highlight up-coming events.

## Home Page Wireframe

![new mockup 1](https://cloud.githubusercontent.com/assets/40253/11311912/ca2883cc-8fa0-11e5-8227-7049e0df8c76.png)

## Sitemap

![sitemap](https://cloud.githubusercontent.com/assets/40253/11312032/79b75a52-8fa1-11e5-8943-4557be35d279.png)




Let me know what you think. Thanks!

**Comment by benichu** [comment]
you are the man.

![](http://www.jewishjournal.com/images/made/e52c9891b2873d62/dos-equis-guy_300_232_c1.JPG)

**Comment by sophiedeziel** [comment]
For the front page, should we have a single column feed? It’s (a little bit) easier to have a nice display on mobile from the get go. (It's useful the day of the event when people need the exact address or something like that)

**Comment by nicholasjhenry** [comment]
Great question/suggestion, I was thinking that from a responsive point of view the side bar would move to  the top on smaller devices -- which would be nice as the most recent event would be at the top.

**Comment by nicholasjhenry** [comment]
@sophiedeziel So maybe a walk through would be appropriate for this -- I'll be online Saturday morning if you're up for a hangout.

**Comment by benichu** [comment]
I think the 2 columns layout is great, collapsing to 1 col with the "upcoming events" sidebar at the top when viewing on mobile.

**Comment by sophiedeziel** [comment]
Yep, that solution is the best!
