### ISSUE TITLE
Manage and display news items

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#5]
We need a news feed (kind of blog) to post other items that are not events.

**Comment by itsWill** [comment]
hey I'm picking up this one

**Comment by nicholasjhenry** [comment]
Some outstanding tasks on this:

- [ ] add Enum for state (see Page for an example)
- [ ] link the new item from index view to show view

**Comment by karimmtarek** [comment]
I'll work on the outstanding tasks.

**Comment by benichu** [comment]
I think this issue is completed

**Comment by karimmtarek** [comment]
ooops my bad, should it be closed?

**Comment by benichu** [comment]
Closed

**Comment by nicholasjhenry** [comment]
Opening this again as there our outstanding tasks:

https://github.com/montrealrb/Montreal.rb/issues/5#issuecomment-162028838

(please verify that the outstanding tasks in the checklist have been completed before closing)
