### ISSUE TITLE
Clean-up Models/DB Schema

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#56]
Before the workshop I'm going to clean up the schema -- here's a heads up on what I plan to do:

- [x] votes, remove table (no plan for use)
- [x] users, remove bio (will have members model)
- [x] remove bio for talks
- [x] talks, remove table (not translated)
- [x] rename companies -> organizations

Let me know if there are any concerns.

**Comment by sophiedeziel** [comment]
We can remove `bio` for `talks` since that info is in the `member` model

**Comment by benichu** [comment]
:+1:
