### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#58]
The administration tool should require an authenticated user.

**Comment by karimmtarek** [comment]
me and @em77 @marina101 we'll work on that one

**Comment by karimmtarek** [comment]
I'm not sure if [that pull]( https://github.com/montrealrb/Montreal.rb/pull/75) request resolves this issue or there is more work needs to be done? please advice

**Comment by karimmtarek** [comment]
@nicholasjhenry if there are still some work needs to be done to close this I can work on that, please let me know.

**Comment by cawel** [comment]
@karimmtarek PR #75 indeed allows a user to sign in/out, and even includes nice capybara specs :) 

But as it stands now, nothing prevents a user *not signed in* to actually browse the admin interface (the pages under "/admin"). And I believe this is what that issue was about.

**Comment by karimmtarek** [comment]
@cawel thanks for the feedback I'll work on that, should be done soon.

**Comment by nicholasjhenry** [comment]
- [ ] authorize users to access the back-office
