### ISSUE TITLE
Allow the body of news items and events to be written in markdown

### ISSUE THREAD

**Issue by itsWill** [montrealrb/Montreal.rb#83]
It would be cool if for news items and events we could write the body in markdown to give our posts some :star: :gem: :star: :gem: :star: :gem: :star:.  Thinking we could implement this using something like [redcarpet](https://github.com/vmg/redcarpet)

**Comment by cawel** [comment]
Good idea! I believe @nicholasjhenry told me that was indeed in the pipeline. Pending the core team's approval (e.g. by tagging the issue as a 'feature'), I'd be happy to start on that one.

**Comment by itsWill** [comment]
I've implemented something like this before, so let me know if you need some pointers on how to tackle this one.

**Comment by benichu** [comment]
:+1:

@cawel do you want to take care of it? Also, remember that the markdown storage/display behaviour should be shared by a lot of our models (anywhere we have a `description` or `body` fields I believe, source: https://github.com/montrealrb/Montreal.rb/issues/47#issuecomment-158508238)

**Comment by cawel** [comment]
@benichu Sure thing :+1:  I will start on that tomorrow Tuesday.

**Comment by benichu** [comment]
Cool stuff. I invited you to the contributor's team, so you don't have to fork the repository but can directly create branches off the repository. Tell me if you need any help.

**Comment by nicholasjhenry** [comment]
One additional feature on Events and NewsItems would be to include a `filter` attribute to specify if it's in `markdown` or `html`. This would help with rendering legacy content imported from Wordpress.

**Comment by cawel** [comment]
@itsWill Thanks for the offer. I've been writing my own notes – on various topics – using the awesome markdown syntax for many years now. I should be good! But I'll be looking forward to hear what you have to say in a possible code review ;)

@benichu Thanks for making me a contributor :bow:

@nicholasjhenry Happy if I make your `filter` attribute an enum with 2 possibles options (`markdown` and `html`)? I would speculate that this attribute will be useful initially when rendering the legacy content in its original `html`. But once all that legacy content will be converted to markdown (some months from now), the idea is to get rid of that attribute and only support markdown for _all_ user-defined content.

Taking a look at the [object model diagram](https://github.com/montrealrb/Montreal.rb/issues/47#issuecomment-158508238), my understanding is that "markdown support" is required for the following models:

* `Event`
* `Job`
* `NewsItem`
* `Organization`
* `Page`
* `Talk`

So just to double check, `Event` and `NewsItem` are the only models which should have that special `filter` attribute?

**Comment by nicholasjhenry** [comment]
> So just to double check, Event and NewsItem are the only models which should have that special filter attribute?

Correct. Thank you.

**Comment by benichu** [comment]
@nicholasjhenry Did you have a chance to get a copy of the current wordpress site db dump?
I am curious to know if the content could be converted to markdown when we import instead of implementing a legacy feature that could be (easily, maybe) avoided.
Or, is it a bit too optimistic? Let's have a look at that data.

cc @sophiedeziel

**Comment by nicholasjhenry** [comment]
@benichu Yes, I do have a copy of the dump. Never considered converting the HTML to markdown, but if that's doable sounds like a plan. I'll share the dump with you via slack.

**Comment by benichu** [comment]
@cawel I am going to look into the wordpress db dump (asap)...
In the meantime just focus that feature on displaying raw markdown content, no `filter` unless we have a hard time converting the old content to markdown.

**Comment by cawel** [comment]
@benichu Understood. New PR created for markdown support phase 1: #89.

**Comment by nicholasjhenry** [comment]
Actually, another thought -- doesn't the markdown renderer ignore HTML anyway and passes it through?

**Comment by cawel** [comment]
@nicholasjhenry You are right. Per the [Markdown syntax spec](https://daringfireball.net/projects/markdown/syntax#html), `HTML` code can be inlined. I tested it to confirm that the `redcarpet` gem would indeed respect the spec, and it does. :ok_hand:

**Comment by nicholasjhenry** [comment]
- [ ] I know that this is a work in progress - just a heads up it would be nice to render markdown fields in the admin. Example:

<img width="947" alt="screenshot 2015-12-04 11 47 55" src="https://cloud.githubusercontent.com/assets/40253/11595340/e2349988-9a7c-11e5-95f6-de09362f0c06.png">
