### ISSUE TITLE
Manage and display job postings

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#9]
We need a job board where company needs to sponsor/pay to display a job on it.

The payment can be done offline.

**Comment by anonyo** [comment]
I did this one.

**Comment by nicholasjhenry** [comment]
Brilliant! :party: Do you want to send a pull request for it?

**Comment by nicholasjhenry** [comment]
Some outstanding tasks on this:

- [ ] render a jobs index
- [ ] render a jobs show

**Comment by anonyo** [comment]
I'm on it, I'll have a PR shortly!
