### ISSUE TITLE
Heroku application failed to start after being auto-deployed by CI

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#91]
![](http://storage.thouret.com.s3.amazonaws.com/monosnap/Application_Error_2015-12-01_19-24-17.png)

Source: https://montreal-rb.herokuapp.com/

**Comment by benichu** [comment]
@sophiedeziel do you have access to the logs? do you need a hand with this?

**Comment by sophiedeziel** [comment]
I'll have to look at it tomorrow. I'll give you access to the heroku app too. And @nicholasjhenry.

**Comment by nicholasjhenry** [comment]
Working on this now.

**Comment by benichu** [comment]
Current exception:

```
/app/app/dashboards/page_dashboard.rb:14:in `<class:PageDashboard>': uninitialized constant Administrate::Field::EnumField (NameError)
```

**Comment by nicholasjhenry** [comment]
Got it!

**Comment by benichu** [comment]
we are like twins!

**Comment by nicholasjhenry** [comment]
yip -- we share a brain ;-)

**Comment by benichu** [comment]
You are the Gino Vannelli of GitHub: https://www.youtube.com/watch?v=g2-wE-J91JU

> :musical_note: Living Inside Github :musical_note:

**Comment by nicholasjhenry** [comment]
I'm very jealous of that hair.

**Comment by benichu** [comment]
Everyone is.
Fun Fact, If I let my hair grow, it looks the same :haircut:

**Comment by nicholasjhenry** [comment]
Do it!

**Comment by benichu** [comment]
I tried several times... BIG FAIL
So I decided to focus on different hair

![](http://ecx.images-amazon.com/images/I/91cwlO3tSVL._SL1400_.jpg)

**Comment by nicholasjhenry** [comment]
I won't be able to sleep tonight. :grimacing:
