### ISSUE TITLE
Error when try to create an event with an empty form

### ISSUE THREAD

**Issue by karimmtarek** [montrealrb/Montreal.rb#94]
Below is the error I got when I tried to create an event with an empty form
<img width="1223" alt="screen shot 2015-12-01 at 9 52 40 pm" src="https://cloud.githubusercontent.com/assets/5586031/11520958/f0b91f28-9875-11e5-8bf7-01d43d8d4add.png">

**Comment by sophiedeziel** [comment]
Oh, this is database-level validation. We should shield it by having active record validations

**Comment by itsWill** [comment]
this is to do with it violating the [schema](https://github.com/montrealrb/Montreal.rb/blob/master/db/schema.rb#L34). We can prevent this with validations at the model.

**Comment by cawel** [comment]
Since that issue was really simple, I pushed a fix to the `master` branch directly. See [commit](https://github.com/montrealrb/Montreal.rb/commit/104bda6a34e5b6dd8957918e6c1b66bf7691a73b).

**Comment by cawel** [comment]
As well as some specs for that `Event` model (see [commit](https://github.com/montrealrb/Montreal.rb/commit/b8701b6c5e0b3362390771626ee78e88da2d72f8)).

**Comment by nicholasjhenry** [comment]
thank you for handling this @cawel
