### ISSUE TITLE
What gem groups are being installed on heroku?

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#97]
Source: https://devcenter.heroku.com/articles/bundler#specifying-gems-and-groups

**Comment by nicholasjhenry** [comment]
@benichu I've set the BUNDLE_WITHOUT:

```
 heroku config:set BUNDLE_WITHOUT="development:test"
```

**Comment by benichu** [comment]
I'll do `heroku config:set BUNDLE_WITHOUT="development:test:legacy"` to avoid my special import rake task dependencies...

```ruby
group :legacy do
  gem 'mysql2'
  gem 'reverse_markdown'
  gem 'nokogiri'
end
```

**Comment by nicholasjhenry** [comment]
Nice. :+1:
